package:
    name: pydvid

source:
  path: ../

requirements:
  build:
    - python >=3.8
    - setuptools

  run:
    - python
    - requests
    - numpy >=1.17
    - h5py
    - pandas <1.0
    - numba >=0.45
    - vigra
    - dvidutils >=0.0.post81
    - tqdm
    - ujson
    - pykafka
    - networkx >=2.1
    - asciitree
    - protobuf

    # Optional dependencies
    #- graph-tool  # <-- Faster connected-components for very large graphs
    #- nifty       # <-- Alternative cleaving algorithm "seeded-watershed"

test:
  requires:
    - pytest
    - dvid >=dvid-0.9.6.post64
    - libdvid-cpp

  imports:
    - dvid

  commands:
    - pytest -s --tb=native --pyargs pydvid.tests

about:
  home: https://github.com/brain-map/pydvid
  license: BSD (3-clause)
  summary: Python tool for interacting with a DVID server.
